spring:
  application:
    name: content-service
  # Go to localhost:<Port>/h2-console to view h2 db
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

server:
  port: 8080

grpc:
  client:
    keyService:
      address: static://localhost:8081
      negotiation-type: plaintext

